__How many multiplications and additions do you need to perform a matrix multiplication between a (n, k) and (k, m) matrix? Explain.__

A single row and a column have k multiplications and n-1 additions. Hence, total no. of multiplications would be k * n * m and additions would be n-1 * n * m.

__Write Python code to multiply the above two matrices. Solve using list of lists and then use numpy. Compare the timing of both solutions. Which one is faster? Why?__

In [2]:
import numpy as np
n=3; m=4; k=3;
A=np.random.randint(10,size=(n,k))
B=np.random.randint(10,size=(k,m))
print(A)

[[8 6 4]
 [6 5 2]
 [4 1 1]]


In [4]:
#list of lists method
res=[[None]*m, [None]*m, [None]*m]#using *n updates all rows (undesirable)
for x in range (0,n):
    for y in range (0,m):
        ele=0
        for z in range (0,k):
            ele+=A[x,z]*B[z,y]
        res[x][y]=ele
print(res)

[[42, 110, 64, 32], [23, 87, 48, 16], [10, 37, 22, 8]]


In [5]:
np_res=np.dot(A,B)
print(np_res)

[[ 42 110  64  32]
 [ 23  87  48  16]
 [ 10  37  22   8]]


Surprisingly the numpy dot method is slower. Probably considering each element as complex numbers and hence leading to an increase in multiplication and addition operations.

__Finding the highest element in a list requires one pass of the array. Finding the second highest element requires 2 passes of the the array. Using this method, what is the time complexity of finding the median of the array? Can you suggest a better method? Can you implement both these methods in Python and compare against numpy.median routine in terms of time?__

If n is the no. of elements in an array/list, to find the maximum element, n elements would need to be iterated over i.e. O(n). To get the 2nd maximum element, another n-1 iterations would be required i.e. O(n-1). Hence, in order to obtain the median, n*...(n+1)/2 in case n is odd and n*..(n/2)+1 in case n is even iterations are required.

In [17]:
l1=[1, 7, 2, 3, 4] #assuming all positive and non repeating
n=len(l1)
max=19999
for i in range (0,(n+1)//2):
    maxPrev=max#very high number initially
    max=l1[0]
    for j in range (1,n):
        maxi=l1[j]
        if maxi>max and maxi<maxPrev:
            max=maxi

print(max)

3


In [21]:
li=[1,7,2,3,4]
#maxi=[li[-1]] #only if n is odd 
min=li[-1]
for i in range(0,n-1,2):
    if li[i]>=li[i+1]:
        ele=li[i]
        #maxi.append(li[i])
    else:
        ele=li[i+1]
        #maxi.append(li[i+1])
    if ele<min:
        min=ele
#min=maxi[0]
#for i in range (1,(n+1)//2):
    #ele=maxi[i]
    #if ele<min:
        #min=ele
print(min)

3


In [22]:
li=[1,7,2,3,4]
med=np.median(li)
print(med)

3.0


__What is the gradient of the following function with respect to x and y?__

Gradient with respect to x = $$2xy+y^3cos(x)$$

Gradient with respect to y = $$ x^2+3y^2sin(x)$$

__Use JAX to confirm the gradient evaluated by your method matches the analytical solution corresponding to a few random values of x and y__

In [37]:
import jax
import jax.numpy as jnp
x=0.1; y=0.2;
def f(x,y):
    return x**2*y+y**3*jnp.sin(x)
grad_fy=jax.grad(f,argnums=1)
grad_fx=jax.grad(f,argnums=0)
valx_jax=grad_fx(x,y)
valx=2*x*y+y**3*np.cos(x)
valy=x**2+3*y**2*np.sin(x)
valy_jax=grad_fy(x,y)
print(valy)
print(valy_jax)


0.021980009997619385
0.02198001


__Use sympy to confirm that you obtain the same gradient analytically.__

In [49]:
import sympy as sym
#from sympy.abc import x, y
x,y=sym.symbols('x,y')
exp=x**2*y+y**3*sym.sin(x)
v=list(sym.ordered(exp.free_symbols))
gradient=lambda f,v: sym.Matrix([f]).jacobian(v)
print(gradient(exp,v))

Matrix([[2*x*y + y**3*cos(x), x**2 + 3*y**2*sin(x)]])
